  
task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  env_script:
    - env
  clone_script:
    - repo init --depth=1 -u git:///github.com/Wave-Project/manifest -b r
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/krishiv8190/device_xiaomi_sakura-2 device/xiaomi/sakura
    - git clone https://github.com/geopd/vendor_xiaomi_sakura vendor/xiaomi
    - git clone https://github.com/darkhz/revvz_sakura kernel/xiaomi/msm8953
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
  build_script:
    - source build/envsetup.sh
    - brunch sakura
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }
    up out/target/product/sakura/*.zip
